spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true

  redis:
        host: localhost
        port: 6379
        password: 123456
        timeout: 5000
        jedis:
          pool:
            max-idle: 10
            max-wait: 100000

server:
  port: 8082
  servlet:
    context-path: /sell